### PR TITLE
Fix compilation error '<symbol> changed binding to STB_GLOBAL'

### PR DESCRIPTION
**Pull request by gemesa**
I am using HighTec Rust Aurix compiler version 1.0.0 but I assume this solution works with 0.2.0 as well.

### CODE REVIEW

**Comment by alepez** [comment]
Hi @gemesa. This repo exists as an example for the compiler problem I issued to Horst some days ago. I prefer to keep the solution in a separate branch.

I understand what is the problem in my implementation: the symbol is defined multiple times in the same translation unit with different directives. 

I feel it kind of weird, because there are two different behaviors when compiled with or without optimization. But if we can say that the same symbol cannot exist multiple times in the same translation unit, it makes sense to define the weak one in a different crate.

**Comment by gemesa** [comment]
Hey @alepez, it is not related to the optimization level. There are differences other than the optimization level `-C opt-level=3` between the debug and release builds, including `-C incremental=...`, which is responsible for this behavior.

When you perform an incremental build (enabled by default in debug builds), the compiler treats your runtime module as a separate translation unit and generates a distinct object file. Check the following minimal example:

```rust
#![no_main]
#![no_std]

use core::panic::PanicInfo;

#[panic_handler]
fn panic(_info: &PanicInfo) -> ! { loop {} }

#[export_name = "main"]
fn main() -> ! {
    loop {}
}

#[export_name = "Crt0PreInit"]
fn pre_init_fn() {}

mod runtime {
    use core::arch::global_asm;

    global_asm!(
        ".weak Crt0PostInit",
        ".type Crt0PostInit, %function",
        "Crt0PostInit:",
        "ret",
    );

    global_asm!(
        ".weak Crt0PreInit",
        ".type Crt0PreInit, %function",
        "Crt0PreInit:",
        "ret",
    );
}

```

```
> cargo build --target=tc162-htc-none --verbose
   Compiling can v0.1.0 (C:\Users\andra\git-repos\aurix-rust-release-build-issue-example-original)
...
     Running `rustc --crate-name can --edition=2021 src\main.rs ... -C incremental=C:\Users\andra\git-repos\aurix-rust-release-build-issue-example-original\target\tc162-htc-none\debug\incremental ...`
    Finished dev [unoptimized + debuginfo] target(s) in 1.07s
> llvm-objdump --syms .\target\tc162-htc-none\debug\incremental\main-1fi8eb56miayz\s-gvp3lv5ovu-1kt0u6-d2dckzi6tgaxvn4yk8co0vcv1\4bsfi2hxy692kpnr.o

.\target\tc162-htc-none\debug\incremental\main-1fi8eb56miayz\s-gvp3lv5ovu-1kt0u6-d2dckzi6tgaxvn4yk8co0vcv1\4bsfi2hxy692kpnr.o:        file format elf32-tricore

SYMBOL TABLE:
00000000 l    df *ABS*  00000000 4bsfi2hxy692kpnr
00000000  w    F .text  00000000 Crt0PostInit
00000002  w    F .text  00000000 Crt0PreInit
> llvm-objdump --syms .\target\tc162-htc-none\debug\incremental\main-1fi8eb56miayz\s-gvp3lv5ovu-1kt0u6-d2dckzi6tgaxvn4yk8co0vcv1\4ipuw7paadoayveq.o

.\target\tc162-htc-none\debug\incremental\main-1fi8eb56miayz\s-gvp3lv5ovu-1kt0u6-d2dckzi6tgaxvn4yk8co0vcv1\4ipuw7paadoayveq.o:        file format elf32-tricore

SYMBOL TABLE:
00000000 l    df *ABS*  00000000 4ipuw7paadoayveq
00000000 g     F .text.rust_begin_unwind        00000004 .hidden rust_begin_unwind
00000000 g     F .text.main     00000004 main
00000000 g     F .text.Crt0PreInit      00000002 Crt0PreInit
```
